problem_id: A-n64-k9-routecap4-transfer2
dataset: A
problem_type: scvrp
n_customers: 64
vehicle_count: 9
capacity: 100
best_known:
coords:
  -   - 97
      - 33
  -   - 57
      - 81
  -   - 1
      - 33
  -   - 55
      - 57
  -   - 29
      - 37
  -   - 21
      - 39
  -   - 93
      - 37
  -   - 5
      - 91
  -   - 25
      - 11
  -   - 47
      - 37
  -   - 87
      - 25
  -   - 67
      - 65
  -   - 71
      - 89
  -   - 67
      - 15
  -   - 45
      - 79
  -   - 71
      - 57
  -   - 29
      - 1
  -   - 59
      - 79
  -   - 93
      - 83
  -   - 47
      - 41
  -   - 51
      - 41
  -   - 23
      - 93
  -   - 87
      - 95
  -   - 39
      - 45
  -   - 45
      - 7
  -   - 85
      - 51
  -   - 35
      - 93
  -   - 47
      - 79
  -   - 59
      - 91
  -   - 83
      - 51
  -   - 49
      - 65
  -   - 21
      - 55
  -   - 51
      - 21
  -   - 69
      - 43
  -   - 37
      - 41
  -   - 37
      - 95
  -   - 5
      - 71
  -   - 37
      - 47
  -   - 83
      - 73
  -   - 17
      - 71
  -   - 5
      - 71
  -   - 81
      - 17
  -   - 59
      - 33
  -   - 63
      - 87
  -   - 21
      - 77
  -   - 71
      - 51
  -   - 21
      - 17
  -   - 9
      - 7
  -   - 65
      - 43
  -   - 25
      - 63
  -   - 13
      - 57
  -   - 47
      - 43
  -   - 77
      - 9
  -   - 57
      - 55
  -   - 21
      - 33
  -   - 27
      - 59
  -   - 83
      - 9
  -   - 63
      - 69
  -   - 9
      - 35
  -   - 25
      - 55
  -   - 33
      - 3
  -   - 53
      - 11
  -   - 51
      - 49
  -   - 9
      - 23
demands:
  - 0
  - 10
  - 15
  - 23
  - 23
  - 24
  - 17
  - 1
  - 4
  - 2
  - 5
  - 18
  - 9
  - 8
  - 23
  - 13
  - 4
  - 18
  - 16
  - 26
  - 16
  - 4
  - 23
  - 8
  - 26
  - 16
  - 5
  - 2
  - 21
  - 23
  - 8
  - 5
  - 8
  - 26
  - 12
  - 8
  - 3
  - 8
  - 19
  - 16
  - 2
  - 3
  - 17
  - 7
  - 5
  - 8
  - 4
  - 12
  - 19
  - 19
  - 26
  - 24
  - 5
  - 8
  - 22
  - 9
  - 18
  - 19
  - 15
  - 5
  - 11
  - 12
  - 54
  - 8
fixed_routes:
  -   - 34
      - 4
      - 5
      - 54
  -   - 6
      - 25
      - 29
  -   - 49
      - 39
      - 44
      - 30
  -   - 56
      - 52
      - 41
      - 10
  -   - 18
      - 22
      - 12
      - 38
  -   - 46
      - 63
      - 2
      - 58
  -   - 59
      - 31
      - 50
      - 55
  -   - 36
      - 40
      - 7
      - 21
  -   - 51
      - 23
      - 37
      - 62
  -   - 53
      - 3
      - 57
      - 11
  -   - 32
      - 24
      - 61
      - 13
  -   - 17
      - 1
      - 28
      - 43
  -   - 20
      - 19
      - 9
      - 42
  -   - 27
      - 14
      - 26
      - 35
  -   - 33
      - 48
      - 45
      - 15
  -   - 8
      - 47
      - 16
      - 60
fixed_route_capacities:
  - 34
  - 33
  - 13
  - 8
  - 25
  - 12
  - 10
  - 3
  - 16
  - 26
  - 16
  - 17
  - 18
  - 7
  - 21
  - 8
